### ISSUE TITLE
Host your own questions

### ISSUE THREAD

**Issue by SparcImagination** [AnushanLingam/OpenTrivia#6]
Is there a way to host your own question database without the need of the Opentdb API??

**Comment by AnushanLingam** [comment]
I looked for any sort of API that allowed me to download all the questions so I can host them locally but I couldn't find anything.


The only way I could think of was writing a script to pull 50 questions at a time (the max for Opentdb I believe.) from the API and populating a local database with it but I was fine with using an API at the time so I didn't bother.


If you already have the questions then it's just a matter of replacing the API calls with the appropriate database queries.
